insert into users(username,password,rol) values ("user","userpassword","ROLE_USER");
insert into users(username,password,rol) values ("editor","editorpassword","ROLE_EDITOR");

insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("TM25CEZ",2,"Audi","A3","Negru",2008,1900,"Diesel",136,2000,500,4.800);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("HD37ABT",2,"Dacia","Logan","Rosu",2006,1400,"Benzina",85,1500,350,2.000);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("HD10UML",2,"BMW","M3","Gri",2015,2700,"Diesel",250,2700,500,14.800);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("TM98ALP",2,"Hyundai","I30","Rosu",2020,1500,"Diesel",110,2000,500,4.800);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("TM23ASJ", 2, "Renault", "Clio", "Alb", 2019, 1200, "Benzină", 90, 1500, 300, 7500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("CT82JKP", 2, "Volkswagen", "Golf", "Negru", 2018, 1400, "Diesel", 110, 2000, 400, 9500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("HD28MLP", 2, "Ford", "Focus", "Gri", 2017, 1300, "Benzină", 100, 1800, 350, 8200);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("HD82CLA", 2, "Toyota", "Corolla", "Albastru", 2016, 1600, "Benzină", 120, 2200, 400, 10500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("CS27MLA", 2, "BMW", "Seria 3", "Negru", 2019, 2000, "Diesel", 150, 2800, 500, 24000);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("GJ72JAS", 2, "Audi", "A4", "Argintiu", 2017, 1800, "Benzină", 140, 2500, 450, 18500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("TM82CJI", 2, "Mercedes-Benz", "Clasa C", "Roșu", 2018, 1900, "Diesel", 170, 3000, 550, 26500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("TM11MAL", 2, "Ford", "Fiesta", "Verde", 2015, 1200, "Benzină", 80, 1200, 300, 6500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("BH81MNN", 2, "Honda", "Civic", "Alb", 2017, 1500, "Benzină", 100, 1800, 400, 8500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("BH61NNA", 2, "Opel", "Astra", "Gri", 2018, 1400, "Diesel", 110, 2000, 420, 9200);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("TM57KKG", 2, "Skoda", "Octavia", "Argintiu", 2016, 1600, "Diesel", 120, 2200, 450, 10500);
insert into masini(nr_inmatriculare, id_utilizator, marca, model, culoare, an_fabricatie, capacitate, combustibil, putere, cuplu, volum_portbagaj, pret) values ("HD33ALX", 2, "Renault", "Megane", "Albastru", 2019, 1800, "Benzină", 130, 2400, 500, 11500);
